spring:
  
  application:
    name: Poro-MeetLink

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/poromeetlink?useSSL=false
    username: postgres
    password: admin

  messages:
    basename: messages
    encoding: UTF-8

  profiles:
    active: dev
  jackson:
    serialization:
      write_dates_as_timestamps: false
  http:
    encoding:
      charset: UTF-8
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    url: jdbc:postgresql://localhost:5432/poromeetlink?useUnicode=true&characterEncoding=utf8&useSSL=false
    user: postgres
    password: admin
    check-change-log-location: true
    drop-first: false

server:
  port: 8080
  servlet:
    context-path: /poromeetlink
logging:
  file: poro_meet_link.log
  level:
    root: info






